name: minex
description: تطبيق سوق مفتوح للبيع والشراء

publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.2
  intl: ^0.20.2
  url_launcher: ^6.3.0
  flutter_image_compress: ^2.3.0
  fl_chart: ^0.68.0
  video_player: ^2.8.6 # تم تخفيض الإصدار قليلاً للتوافق
  photo_view: ^0.15.0
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2 # تم تحديث هذا ليتوافق مع core
  flutter_local_notifications: ^17.0.0 
  cloud_firestore: ^4.0.0
  font_awesome_flutter: ^10.7.0
  collection: ^1.18.0
  share_plus: ^7.0.1
  app_links: ^6.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/job.png
    - assets/images/tenders.png
    - assets/images/suppliers.png
    - assets/images/general_offers.png
    - assets/images/cars.png
    - assets/images/motorcycles.png
    - assets/images/real_estate.png
    - assets/images/weapons.png
    - assets/images/electronics.png
    - assets/images/electrical.png
    - assets/images/animals.png
    - assets/images/agriculture.png
    - assets/images/food.webp
    - assets/images/restaurants.webp
    - assets/images/heating.png
    - assets/images/accessories.webp
    - assets/images/house_rent.png
    - assets/images/books.webp
    - assets/images/home_health.png
    - assets/images/clothing_shoes.webp
    - assets/images/furniture.png
    - assets/images/wholesalers.png
    - assets/images/distributors.png
    - assets/images/others.png
  uses-material-design: true